version: '3'
services:
  web:
    build: 
      context: ./nginx
      dockerfile: dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend
  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api